# Generated by Django 5.0.4 on 2024-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
