# Generated by Django 5.0.7 on 2024-08-21 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_auto_20240821_1509"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="project",
        ),
        migrations.RenameField(
            model_name="choice",
            old_name="project_2",
            new_name="project",
        ),
    ]
