# Generated by Django 5.0.8 on 2024-08-29 14:10

import data.models
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_alter_choice_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_id",
                    utils.fields.UpperCharField(
                        default=data.models.generate_analysis_id,
                        max_length=12,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
