# Generated by Django 5.0.8 on 2024-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0008_project_analysis_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="constraints",
            field=models.ManyToManyField(to="data.choice"),
        ),
    ]
