# Generated by Django 5.0.8 on 2024-09-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("data", "0011_remove_project_analysis_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
    ]
