# Generated by Django 5.0.8 on 2025-01-14 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0012_alter_project_content_type"),
        ("mscape", "0023_remove_mscape_analyses_remove_openmgs_analyses_and_more"),
        ("pathsafe", "0009_remove_pathsafe_analyses"),
        ("testproject", "0011_remove_testmodel_analyses"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Analysis",
        ),
    ]
