# Generated by Django 5.0.8 on 2025-01-14 12:13

import data.models
import django.db.models.deletion
import simple_history.models
import utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("data", "0013_delete_analysis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Indicator for whether a project record has been published.",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        help_text="The date the project record was published in Onyx.",
                        null=True,
                    ),
                ),
                (
                    "is_suppressed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicator for whether a project record has been hidden from users.",
                    ),
                ),
                (
                    "is_site_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicator for whether a project record has been hidden from users not within the record's site.",
                    ),
                ),
                (
                    "analysis_id",
                    utils.fields.UpperCharField(
                        default=data.models.generate_analysis_id,
                        help_text="Unique identifier for an analysis in Onyx.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        help_text="The date the analysis was carried out."
                    ),
                ),
                ("name", utils.fields.StrippedCharField(max_length=100, unique=True)),
                ("command_details", models.TextField(blank=True)),
                ("pipeline_details", models.TextField(blank=True)),
                ("experiment_details", models.JSONField(default=dict)),
                ("result", models.TextField(blank=True)),
                ("report", models.TextField(blank=True)),
                ("outputs", models.TextField(blank=True)),
                (
                    "identifiers",
                    models.ManyToManyField(
                        related_name="analyses", to="data.anonymiser"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="data.project"
                    ),
                ),
                (
                    "site",
                    utils.fields.SiteField(
                        help_text="Site that uploaded the record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.site",
                        to_field="code",
                    ),
                ),
                (
                    "upstream_analyses",
                    models.ManyToManyField(
                        related_name="downstream_analyses", to="data.analysis"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalAnalysis",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("last_modified", models.DateTimeField(blank=True, editable=False)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Indicator for whether a project record has been published.",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        help_text="The date the project record was published in Onyx.",
                        null=True,
                    ),
                ),
                (
                    "is_suppressed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicator for whether a project record has been hidden from users.",
                    ),
                ),
                (
                    "is_site_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicator for whether a project record has been hidden from users not within the record's site.",
                    ),
                ),
                (
                    "analysis_id",
                    utils.fields.UpperCharField(
                        db_index=True,
                        default=data.models.generate_analysis_id,
                        help_text="Unique identifier for an analysis in Onyx.",
                        max_length=12,
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        help_text="The date the analysis was carried out."
                    ),
                ),
                ("name", utils.fields.StrippedCharField(db_index=True, max_length=100)),
                ("command_details", models.TextField(blank=True)),
                ("pipeline_details", models.TextField(blank=True)),
                ("experiment_details", models.JSONField(default=dict)),
                ("result", models.TextField(blank=True)),
                ("report", models.TextField(blank=True)),
                ("outputs", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="data.project",
                    ),
                ),
                (
                    "site",
                    utils.fields.SiteField(
                        blank=True,
                        db_constraint=False,
                        help_text="Site that uploaded the record.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.site",
                        to_field="code",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical analysis",
                "verbose_name_plural": "historical analysiss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
