# Generated by Django 5.0.8 on 2025-08-01 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("data", "0013_analysis_historicalanalysis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="upstream_analyses",
            field=models.ManyToManyField(
                help_text="The analyses that this analysis depends on.",
                null=True,
                related_name="downstream_analyses",
                to="data.analysis",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysis",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("analysis_date__isnull", True),
                    ("analysis_date__lte", models.F("last_modified")),
                    _connector="OR",
                ),
                name="data_analysis_analysi_d4d938_nf",
                violation_error_message="At least one of analysis_date is from the future.",
            ),
        ),
    ]
