# Generated by Django 5.1.10 on 2025-09-30 11:40

import data.models
import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_analysis_upstream_analyses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_id',
            field=utils.fields.PrimaryIDField(default=data.models.generate_analysis_id, help_text='Unique identifier for an analysis in Onyx.', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalanalysis',
            name='analysis_id',
            field=utils.fields.PrimaryIDField(db_index=True, default=data.models.generate_analysis_id, help_text='Unique identifier for an analysis in Onyx.', max_length=12),
        ),
    ]
