# Generated by Django 5.0.8 on 2025-02-06 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0014_analysis_historicalanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="data_project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_project",
                to="data.project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_analysis_project",
            field=models.BooleanField(default=False),
        ),
    ]
