# Generated by Django 5.1.10 on 2025-10-23 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('data', '0014_alter_analysis_upstream_analyses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysis',
            name='data_analysis_project_8a0c8a_ut',
        ),
        migrations.RemoveConstraint(
            model_name='analysis',
            name='data_analysis_report__f3f0f8_ovg',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='pipeline_command',
            field=models.CharField(blank=True, help_text='Command used to run the pipeline for the analysis.', max_length=200),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='pipeline_url',
            field=models.CharField(blank=True, help_text='URL to the pipeline used for the analysis.', max_length=200),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='result',
            field=models.CharField(blank=True, help_text='Key findings of the analysis.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalanalysis',
            name='pipeline_command',
            field=models.CharField(blank=True, help_text='Command used to run the pipeline for the analysis.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalanalysis',
            name='pipeline_url',
            field=models.CharField(blank=True, help_text='URL to the pipeline used for the analysis.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalanalysis',
            name='result',
            field=models.CharField(blank=True, help_text='Key findings of the analysis.', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_published', True), _negated=True), ('result__isnull', False), _connector='OR'), name='data_analysis_is_publ_37a71c_cvr', violation_error_message='Each of result are required in order to set is_published to the value.'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_published', True), _negated=True), ('report__isnull', False), ('outputs__isnull', False), _connector='OR'), name='data_analysis_is_publ_58138b_cvo', violation_error_message='At least one of report, outputs are required in order to set is_published to the value.'),
        ),
    ]
