# Generated by Django 5.0.8 on 2025-02-11 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0017_alter_project_data_project"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="data_project_is_anal_a9077c_cvr",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_analysis_project",
        ),
    ]
