# Generated by Django 5.0.8 on 2025-03-10 17:40

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0018_remove_project_data_project_is_anal_a9077c_cvr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="name",
            field=utils.fields.StrippedCharField(
                help_text="Unique name for the analysis.", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="name",
            field=utils.fields.StrippedCharField(
                db_index=True, help_text="Unique name for the analysis.", max_length=100
            ),
        ),
    ]
