# Generated by Django 5.0.8 on 2025-03-10 17:43

import utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("data", "0019_alter_analysis_name_alter_historicalanalysis_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="name",
            field=utils.fields.StrippedCharField(
                help_text="Unique name for the analysis.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="name",
            field=utils.fields.StrippedCharField(
                help_text="Unique name for the analysis.", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["project", "analysis_id", "analysis_date", "name"],
                name="data_analys_project_a30aa2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysis",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="data_analysis_project_8a0c8a_ut"
            ),
        ),
    ]
