# Generated by Django 5.0.8 on 2025-03-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0020_alter_analysis_name_alter_historicalanalysis_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="command_details",
            field=models.TextField(blank=True, help_text="Details of the command run."),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="experiment_details",
            field=models.JSONField(
                default=dict, help_text="Details of the experiment run."
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="identifiers",
            field=models.ManyToManyField(
                help_text="Key identifiers involved in the analysis.",
                related_name="analyses",
                to="data.anonymiser",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="outputs",
            field=models.TextField(
                blank=True, help_text="Directory of outputs produced from the analysis."
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="pipeline_details",
            field=models.TextField(
                blank=True, help_text="Details of the pipeline run."
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="report",
            field=models.TextField(
                blank=True, help_text="Report produced from the analysis."
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="result",
            field=models.TextField(blank=True, help_text="The result of the analysis."),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="upstream_analyses",
            field=models.ManyToManyField(
                help_text="The analyses that this analysis depends on.",
                related_name="downstream_analyses",
                to="data.analysis",
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="command_details",
            field=models.TextField(blank=True, help_text="Details of the command run."),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="experiment_details",
            field=models.JSONField(
                default=dict, help_text="Details of the experiment run."
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="outputs",
            field=models.TextField(
                blank=True, help_text="Directory of outputs produced from the analysis."
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="pipeline_details",
            field=models.TextField(
                blank=True, help_text="Details of the pipeline run."
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="report",
            field=models.TextField(
                blank=True, help_text="Report produced from the analysis."
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="result",
            field=models.TextField(blank=True, help_text="The result of the analysis."),
        ),
    ]
