# Generated by Django 5.0.8 on 2025-03-12 15:00

import utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("data", "0021_alter_analysis_command_details_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="analysis",
            name="data_analys_project_a30aa2_idx",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="command_details",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="pipeline_details",
        ),
        migrations.RemoveField(
            model_name="historicalanalysis",
            name="command_details",
        ),
        migrations.RemoveField(
            model_name="historicalanalysis",
            name="pipeline_details",
        ),
        migrations.AddField(
            model_name="analysis",
            name="description",
            field=models.CharField(
                blank=True, help_text="Description of the analysis.", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="pipeline_command",
            field=models.CharField(
                blank=True,
                help_text="Command used to run the pipeline for the analysis.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="pipeline_name",
            field=models.CharField(
                default="default-pipeline-name",
                help_text="Name of the pipeline used for the analysis.",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analysis",
            name="pipeline_url",
            field=models.CharField(
                blank=True,
                help_text="URL to the pipeline used for the analysis.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="pipeline_version",
            field=models.CharField(
                default="0.1.0",
                help_text="Version of the pipeline used for the analysis.",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalanalysis",
            name="description",
            field=models.CharField(
                blank=True, help_text="Description of the analysis.", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="historicalanalysis",
            name="pipeline_command",
            field=models.CharField(
                blank=True,
                help_text="Command used to run the pipeline for the analysis.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalanalysis",
            name="pipeline_name",
            field=models.CharField(
                default="default-pipeline-name",
                help_text="Name of the pipeline used for the analysis.",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalanalysis",
            name="pipeline_url",
            field=models.CharField(
                blank=True,
                help_text="URL to the pipeline used for the analysis.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalanalysis",
            name="pipeline_version",
            field=models.CharField(
                default="0.1.0",
                help_text="Version of the pipeline used for the analysis.",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="experiment_details",
            field=models.JSONField(
                default=dict,
                help_text="Structured details of the experiment run, and/or outcomes.",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="name",
            field=utils.fields.StrippedCharField(
                help_text="Name for the analysis, unique to the project.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="outputs",
            field=models.CharField(
                blank=True,
                help_text="Directory of outputs produced from the analysis.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="report",
            field=models.CharField(
                blank=True,
                help_text="HTML report produced from the analysis.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="result",
            field=models.CharField(
                help_text="Key findings of the analysis.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="experiment_details",
            field=models.JSONField(
                default=dict,
                help_text="Structured details of the experiment run, and/or outcomes.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="name",
            field=utils.fields.StrippedCharField(
                help_text="Name for the analysis, unique to the project.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="outputs",
            field=models.CharField(
                blank=True,
                help_text="Directory of outputs produced from the analysis.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="report",
            field=models.CharField(
                blank=True,
                help_text="HTML report produced from the analysis.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="historicalanalysis",
            name="result",
            field=models.CharField(
                help_text="Key findings of the analysis.", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["project", "analysis_id", "analysis_date", "name", "result"],
                name="data_analys_project_b5c13b_idx",
            ),
        ),
    ]
