# Generated by Django 5.0.8 on 2025-03-12 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("data", "0022_remove_analysis_data_analys_project_a30aa2_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="analysis",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("report__isnull", False),
                    ("outputs__isnull", False),
                    _connector="OR",
                ),
                name="data_analysis_report__f3f0f8_ovg",
                violation_error_message="At least one of report, outputs is required.",
            ),
        ),
    ]
