# Generated by Django 5.0.8 on 2025-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0026_alter_analysis_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="identifiers",
            field=models.ManyToManyField(
                help_text="Key anonymised identifiers involved in the analysis. This does not include the CLIMB ID (for these, see the {project}_records field).",
                related_name="analyses",
                to="data.anonymiser",
            ),
        ),
    ]
