# Generated by Django 5.0.8 on 2025-04-02 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0027_alter_analysis_identifiers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="data_project",
        ),
    ]
