services:
  wsgi:
    build:
      context: .
      target: dev
    volumes:
      - ./onyx:/app
      - ./onyx/projects/testproject:/app/projects/testproject
    environment:
      - ONYX_PROJECTS=${ONYX_PROJECTS},testproject
