# Generated by Django 5.0.3 on 2024-03-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testproject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetestmodel",
            name="collection_month",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="basetestmodel",
            name="received_month",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalbasetestmodel",
            name="collection_month",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalbasetestmodel",
            name="received_month",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaltestmodel",
            name="collection_month",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaltestmodel",
            name="received_month",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaltestmodelrecord",
            name="test_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="historicaltestmodelrecord",
            name="test_start",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="testmodelrecord",
            name="test_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="testmodelrecord",
            name="test_start",
            field=models.DateField(),
        ),
    ]
