# Generated by Django 5.0.3 on 2024-03-21 11:23

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "testproject",
            "0003_remove_basetestmodel_testproject_basetestmodel_is_publ_f136db_cvr_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetestmodel",
            name="run_name",
            field=utils.fields.UpperCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="basetestmodel",
            name="sample_id",
            field=utils.fields.UpperCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalbasetestmodel",
            name="run_name",
            field=utils.fields.UpperCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalbasetestmodel",
            name="sample_id",
            field=utils.fields.UpperCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="historicaltestmodel",
            name="run_name",
            field=utils.fields.UpperCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicaltestmodel",
            name="sample_id",
            field=utils.fields.UpperCharField(max_length=50),
        ),
    ]
