# Generated by Django 5.0.3 on 2024-03-26 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testproject", "0004_alter_basetestmodel_run_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="testmodelrecord",
            index=models.Index(
                fields=["test_id"], name="testproject_test_id_811b7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testmodelrecord",
            index=models.Index(
                fields=["test_pass"], name="testproject_test_pa_4e443f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testmodelrecord",
            index=models.Index(
                fields=["test_start"], name="testproject_test_st_b8932c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testmodelrecord",
            index=models.Index(
                fields=["test_end"], name="testproject_test_en_7043b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testmodelrecord",
            index=models.Index(
                fields=["score_a"], name="testproject_score_a_15c0e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testmodelrecord",
            index=models.Index(
                fields=["score_b"], name="testproject_score_b_2c31f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testmodelrecord",
            index=models.Index(
                fields=["score_c"], name="testproject_score_c_505230_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testmodelrecord",
            index=models.Index(
                fields=["test_result"], name="testproject_test_re_04dc62_idx"
            ),
        ),
    ]
