# Generated by Django 5.0.3 on 2024-04-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testproject", "0005_testmodelrecord_testproject_test_id_811b7e_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testmodel",
            name="basetestmodel_ptr",
        ),
        migrations.AlterField(
            model_name="testmodelrecord",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="testproject.basetestmodel",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestmodelrecord",
            name="link",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="testproject.basetestmodel",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalTestModel",
        ),
        migrations.DeleteModel(
            name="TestModel",
        ),
    ]
