# Generated by Django 5.0.8 on 2024-09-09 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "testproject",
            "0007_rename_historicalbasetestmodel_historicaltestmodel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltestmodel",
            name="scores",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=10
            ),
        ),
        migrations.AddField(
            model_name="testmodel",
            name="scores",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=10
            ),
        ),
    ]
