# Generated by Django 5.0.8 on 2024-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_analysisid"),
        (
            "testproject",
            "0007_rename_historicalbasetestmodel_historicaltestmodel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="identifiers",
            field=models.ManyToManyField(
                related_name="%(class)s_records", to="data.anonymiser"
            ),
        ),
    ]
