# Generated by Django 5.0.8 on 2024-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0010_analysis_delete_analysisid"),
        ("testproject", "0009_historicaltestmodel_structure_testmodel_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="analyses",
            field=models.ManyToManyField(
                help_text="The analyses involving the record.",
                related_name="%(class)s_records",
                to="data.analysis",
            ),
        ),
    ]
