# Generated by Django 5.0.8 on 2025-01-14 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testproject", "0010_testmodel_analyses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testmodel",
            name="analyses",
        ),
    ]
