# Generated by Django 5.0.8 on 2025-03-24 15:19

import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        (
            "testproject",
            "0013_rename_historicaltestmodel_historicaltestproject_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltestproject",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Indicator for whether an object has been published.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestproject",
            name="is_site_restricted",
            field=models.BooleanField(
                default=False,
                help_text="Indicator for whether an object has been hidden from users not within the object's site.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestproject",
            name="is_suppressed",
            field=models.BooleanField(
                default=False,
                help_text="Indicator for whether an object has been hidden from users.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestproject",
            name="published_date",
            field=models.DateField(
                help_text="The date the object was published in Onyx.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaltestproject",
            name="site",
            field=utils.fields.SiteField(
                blank=True,
                db_constraint=False,
                help_text="Site that uploaded the object.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.site",
                to_field="code",
            ),
        ),
        migrations.AlterField(
            model_name="testproject",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Indicator for whether an object has been published.",
            ),
        ),
        migrations.AlterField(
            model_name="testproject",
            name="is_site_restricted",
            field=models.BooleanField(
                default=False,
                help_text="Indicator for whether an object has been hidden from users not within the object's site.",
            ),
        ),
        migrations.AlterField(
            model_name="testproject",
            name="is_suppressed",
            field=models.BooleanField(
                default=False,
                help_text="Indicator for whether an object has been hidden from users.",
            ),
        ),
        migrations.AlterField(
            model_name="testproject",
            name="published_date",
            field=models.DateField(
                help_text="The date the object was published in Onyx.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="testproject",
            name="site",
            field=utils.fields.SiteField(
                help_text="Site that uploaded the object.",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.site",
                to_field="code",
            ),
        ),
    ]
