# Generated by Django 5.1.10 on 2025-09-30 14:50

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0011_remove_testmodel_analyses_squashed_0014_alter_historicaltestproject_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestproject',
            name='climb_id',
            field=utils.fields.PrimaryIDField(db_index=True, help_text='Unique identifier for a project record in Onyx.', max_length=12),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='climb_id',
            field=utils.fields.PrimaryIDField(help_text='Unique identifier for a project record in Onyx.', max_length=12, unique=True),
        ),
    ]
