# Generated by Django 5.1.10 on 2025-10-23 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('data', '0015_remove_analysis_data_analysis_project_8a0c8a_ut_and_more'),
        ('testproject', '0011_remove_testmodel_analyses_squashed_0014_alter_historicaltestproject_is_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestproject',
            name='optional_when_published_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaltestproject',
            name='optional_when_published_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testproject',
            name='optional_when_published_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testproject',
            name='optional_when_published_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='testproject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_published', True), _negated=True), ('optional_when_published_1__isnull', False), ('optional_when_published_2__isnull', False), _connector='OR'), name='testproject_testproject_is_publ_44cc13_cvo', violation_error_message='At least one of optional_when_published_1, optional_when_published_2 are required in order to set is_published to the value.'),
        ),
    ]
