# Generated by Django 5.1.14 on 2026-01-31 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("data", "0015_remove_analysis_data_analysis_project_8a0c8a_ut_and_more"),
        (
            "testproject",
            "0015_historicaltestproject_optional_when_published_1_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltestproject",
            name="unique_together_1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="historicaltestproject",
            name="unique_together_2",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="testproject",
            name="unique_together_1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="testproject",
            name="unique_together_2",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="testproject",
            constraint=models.UniqueConstraint(
                fields=("unique_together_1", "unique_together_2"),
                name="testproject_testproject_unique__369d07_ut",
            ),
        ),
    ]
